# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200, null=True)),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('institucion', models.CharField(max_length=200, null=True)),
                ('codigo_postal', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('calle_numero', models.CharField(max_length=200, null=True)),
                ('apartado_postal', models.CharField(max_length=200, null=True)),
                ('colonia', models.CharField(blank=True, max_length=200, null=True)),
                ('ciudad_y_estado', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
