# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domicilioprofesional',
            old_name='estado_municipio_ciudad',
            new_name='municipio_ciudad',
        ),
    ]
