# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180227_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domicilio',
            old_name='ciudad_y_estado',
            new_name='ciudad',
        ),
        migrations.AddField(
            model_name='domicilioprofesional',
            name='estado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
