# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180227_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domicilioprofesional',
            name='correo_electronico',
        ),
        migrations.AddField(
            model_name='domicilio',
            name='estado',
            field=models.CharField(blank=True, max_length=182, null=True),
        ),
    ]
