# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_division_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='uno',
            field=models.ManyToManyField(related_name='uno', to='account.Division'),
        ),
    ]
