# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_uno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='uno',
            new_name='division_uno',
        ),
    ]
