# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20180416_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='division_uno',
        ),
        migrations.AddField(
            model_name='account',
            name='division_dos',
            field=models.ManyToManyField(related_name='dos', to='account.Division'),
        ),
        migrations.AddField(
            model_name='account',
            name='division_tres',
            field=models.ManyToManyField(related_name='tres', to='account.Division'),
        ),
    ]
