# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20180416_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='division_dos',
        ),
        migrations.RemoveField(
            model_name='account',
            name='division_tres',
        ),
    ]
