# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20180418_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('AGUASCALIENTES', 'AGUASCALIENTES'), ('BAJA CALIFORNIA', 'BAJA CALIFORNIA'), ('BAJA CALIFORNIA SUR', 'BAJA CALIFORNIA SUR'), ('CAMPECHE', 'CAMPECHE'), ('CHIAPAS', 'CHIAPAS'), ('CHIHUAHUA', 'CHIHUAHUA'), ('CIUDAD DE M\xc9XICO', 'CIUDAD DE M\xc9XICO'), ('COAHUILA', 'COAHUILA'), ('COLIMA', 'COLIMA'), ('DURANGO', 'DURANGO'), ('GUANAJUATO', 'GUANAJUATO'), ('GUERRERO', 'GUERRERO'), ('HIDALGO', 'HIDALGO'), ('JALISCO', 'JALISCO'), ('M\xc9XICO', 'M\xc9XICO'), ('MICHOAC\xc1N', 'MICHOAC\xc1N'), ('MORELOS', 'MORELOS'), ('NAYARIT', 'NAYARIT'), ('NUEVO LE\xd3N', 'NUEVO LE\xd3N'), ('OAXACA', 'OAXACA'), ('PUEBLA', 'PUEBLA'), ('QUER\xc9TARO', 'QUER\xc9TARO'), ('QUINTANA ROO', 'QUINTANA ROO'), ('SAN LUIS POTOS\xcd', 'SAN LUIS POTOS\xcd'), ('SINALOA', 'SINALOA'), ('SONORA', 'SONORA'), ('TABASCO', 'TABASCO'), ('TAMAULIPAS', 'TAMAULIPAS'), ('TLAXCALA', 'TLAXCALA'), ('VERACRUZ', 'VERACRUZ'), ('YUCAT\xc1N', 'YUCAT\xc1N'), ('ZACATECAS', 'ZACATECAS')], max_length=45)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cuota',
            options={'ordering': ('fecha_fin',)},
        ),
    ]
